# Change these first
owner: KanteronSystems # Your GitHub username
repo: kanteron-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Kanteron Website
    url: https://www.kanteron.com/
  - name: Kanteron Sitio Web
    url: https://web.kanteron.com/
  - name: Kanteron Blog
    url: https://blog.kanteron.com/
  - name: Blog de Kanteron
    url: https://bloges.kanteron.com/
  - name: Europato
    url: http://europato.kanteron.net/TMIS/login.xhtml
  - name: Azapp
    url: https://azapp.kanteron.net/TMIS/login.xhtml
  - name: GDB Genomics
    url: https://gdb.genomics.kanteron.com/TMIS/login.xhtml   
  - name: K3D
    url: https://k3d.kanteron.net/?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json
  - name: KAV
    url: https://kav.kanteron.net/studylist
  - name: KLS
    url: https://kls.kanteron.net/
  - name: KDV
    url: http://20.185.6.186/KDV/viewer/1.3.6.1.4.1.14519.5.2.1.2193.7172.847236098565581057121195872945
  - name: Central
    url: https://central.kanteron.com/TMIS/login.xhtml
  - name: Testing
    url: https://testing.kanteron.com/TMIS/login.xhtml
  - name: PACS5
    url: https://kanteron-demo-client1.eastus.cloudapp.azure.com/TMIS/secure/historia/Ficha.xhtml?id=1
    
assignees: # Users to assign downtime issues (optional)
  - jcortell

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /kanteron-uptime
  logoUrl: https://blog.kanteron.com/images/logo.png
  name: Uptime
  introTitle: "**Uptime** automatic monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
